version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/ec2-user/temp
  - source:  /dir-symlink
    destination: /home/ec2-user/dir-symlink
  - source:  /file-symlink
    destination: /home/ec2-user/file-symlink/
